---

- name: Remove potentially conflicting packages
  package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true

- name: Ensure Docker package prerequisites are installed
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch="amd64" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
  become: true

- name: Update apt and install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: Add the bones user to the docker OS group
  user:
    name: bones
    groups:
      - docker
    append: true
  become: true

